# Stages are run sequentially
stages:
  - build
  - deploy

# This will run on every branch
build:
  image: node:16    # Run the job in a `node` docker image
  stage: build
  variables:
    # Replace this with your site URL
    PUBLIC_URL: https://abbbacus.gitlab.io/dotcom
  script:
    - yarn install      # Run `yarn install` and `yarn build`
    - yarn build
  artifacts:
    paths:
      - build/          # Save the build result as an artfact

    
pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
