[[redirects]]
  from = "/api/*"
  to = "https://api.abbbacus.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "https://frosty-galileo-2d55e2.netlify.app"
  to = "https://abbbacus.com"
  status = 301
  force = true

